captive_portal:

web_server:
  port: 80

button:
  - platform: restart
    name: "Restart"
    
sensor:
  - platform: wifi_signal
    name: "WiFi"
    update_interval: 60s
    filters:
      - delta: 1
